accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    # ReceiptCreateView,
    create_receipt,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    # path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("create/", create_receipt, name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="categories"),
    path("accounts/", AccountListView.as_view(), name="myaccounts"),
    path(
        "categories/create",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE
    )


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

receipts/forms.py
from django.forms import ModelForm

from receipts.models import Receipt


class ReceiptForm(ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm
    template = "registration/signup.html"
    context = {"form": form}
    return render(request, template, context)

receipts/views.py
from django.forms import ModelChoiceField
from django.shortcuts import render, redirect
from django.urls import Resolver404, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Receipt, ExpenseCategory, Account
from receipts.forms import ReceiptForm


# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


# class ReceiptCreateView(LoginRequiredMixin, CreateView):
#     model = Receipt
#     template_name = "receipts/new_receipt.html"
#     fields = ["vendor", "total", "tax", "date", "category", "account"]
#     success_url = reverse_lazy("home")

#     def form_valid(self, form):
#         form.instance.purchaser = self.request.user
#         return super().form_valid(form)


def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.instance
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
        # form.category = ModelChoiceField(
        #     queryset=Receipt.category.values_list(owner=request.user)
        # )
    context = {"form": form}
    return render(request, "receipts/new_receipt.html", context)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories.html"
    # context_object_name = "expensecategory_list"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/new_category.html"
    fields = ["name"]
    success_url = reverse_lazy("categories")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/new_account.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("myaccounts")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}
        <title>Expense Receipts</title>
        {% endblock title %}
    </head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_staff %}
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'home' %}">My Receipts</a>
                </li>
                <li>
                    <a href="{% url 'categories' %}">My Categories</a>
                </li>
                <li>
                    <a href="{% url 'myaccounts' %}">My Accounts</a>
                </li>
                <li>
                    <a href="{% url 'create_receipt' %}">Create Receipt</a>
                </li>
                <li>
                    <a href="{% url 'create_category' %}">Create Category</a>
                </li>
                <li>
                    <a href="{% url 'create_account' %}">Create Account</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Signup</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav

    </header>
    {% block main %}
    {% endblock main %}
</body>

</html>

receipts/templates/receipts/accounts.html
{% extends 'base.html' %}

{% block title %}
<title>Expense Accounts</title>
{% endblock title %}

{% block main %}
<main>
    <div>
        <h1>My Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
            </thead>
            <tbody>
                {% for name in account_list %}
                <tr>
                    <td>{{ name }}</td>
                    <td>{{ name.number }}</td>
                    <td>{{ name.receipts.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock main %}

receipts/templates/receipts/categories.html
{% extends 'base.html' %}

{% block title %}
<title>Expense Categories</title>
{% endblock title %}

{% block main %}
<main>
    <div>
        <h1>My Expense Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of receipts</th>
            </thead>
            <tbody>
                {% for name in expensecategory_list %}
                <tr>
                    <td>{{ name }}</td>
                    <td>{{ name.receipts.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock main %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block title %}
<title>Receipts</title>
{% endblock title %}

{% block main %}
<main>
    <h1>My Receipts</h1>
    <div>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date | date:"n/j/y" }}</td>
                    <td>{{ receipt.category }}</td>
                    <td>{{ receipt.account }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock main %}

receipts/templates/receipts/new_account.html
{% extends 'base.html' %}

{% block title %}
<title>Create Account</title>
{% endblock title %}

{% block main %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock main %}

receipts/templates/receipts/new_category.html
{% extends 'base.html' %}

{% block title %}
<title>Create Category</title>
{% endblock title %}

{% block main %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock main %}

receipts/templates/receipts/new_receipt.html
{% extends 'base.html' %}

{% block title %}
<title>Create Receipt</title>
{% endblock title %}

{% block main %}
<main>
    <div>
        <h1>Create Receipt</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock main %}